routes/web.php
<?php

use App\Http\Controllers\sessionController;
use App\Http\Controllers\UserReviewController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
})->name('home');

Route::get('/register', 'RegistrationController@create');

Route::post('/register','RegistrationController@store');

Route::get('/login', 'SessionController@create')->name('login');

Route::post('/login', 'SessionController@store');

Route::get('/logout', 'SessionController@destroy');

Route::get('/reviews/create', 'ReviewController@create');

Route::post('/reviews/create', 'ReviewController@store');

Route::get('/reviews', 'ReviewController@index');

Route::get('/reviews/delete/{id}', 'ReviewController@delete');

Route::get('/reviews/show/{id}', 'ReviewController@show');

Route::get('/reviews/show/{id}/commentsexport', 'ExportController@commentExport');

Route::get('/myreviews/reviews/export', 'ExportController@reviewsExport');

Route::post('/reviews/show/{id}', 'ReviewCommentController@store');

Route::get('/reviews/sort/company', 'ReviewController@sortByCompany')->name('sortByCompany');

Route::get('/myreviews', 'UserReviewController@index')->name('myreviews');

Route::post('/myreviews', 'ImportController@importReview')->name('importReviews');

Route::get('/myreviews/sort/bydate', 'UserReviewController@sortByDate')->name('sortByDate');

Route::get('/myreviews/delete/{id}', 'UserReviewController@delete');

Route::resource('user_reviews', 'UserReviewController');

Route::get('/profile', 'ProfileController@index');

Route::post('/profile', 'ProfileController@update_avatar')->name('myprofile');

Route::get('/profile/redact', 'ProfileController@edit');

Route::post('/profile/redact', 'ProfileController@post');

Route::get('/profile/redactpassword', 'ProfileController@editPassword');

Route::post('/profile/redactpassword', 'ProfileController@updatePassword');

Route::get('/profile/review/id/{id}', 'ProfileController@profileReview');

Route::get('/reviews/search', 'ReviewController@search')->name('search');

resources/views/search/index.blade.php
@extends('layouts.app')

@section('title')
Результаты поиска
@endsection

@section('content')
    <div class="container">
        <div class="col-md-8 mr-auto">
            @if(!$reviews->count()==0)
            <h1>Результаты поиска</h1>
            @foreach ($reviews as $review)
                <div class="card mt-3">
                    <div class="card-body">
                        <h5 class="card-title">{{ $review->title }}</h5>
                        <p class="card-text">{{ $review->review_body }}</p>
                        <label for="">Автор:</label>
                        <a href="/profile/review/id/{{$review->createdBy->id}}" class="card-link">{{ $review->createdBy->name }}</a>
                        
                    </div>
                    <div>
                        <a class="mb-1 ml-1 btn btn-primary" href="/reviews/show/{{$review->id}}">Подробнее</a>
                        @if(Auth::check())
                        @if ($review->user_id == Auth::user()->id)
                            <a href="{{ route('user_reviews.edit', $review->id )}}" class="btn btn-primary ml-5 mb-1">Редактировать</a>
                            <a href="/reviews/delete/{{$review->id}}" class="mb-1 btn btn-primary ml-5">Удалить</a>
                        @endif
                        @endif
                    </div>
                </div>
            @endforeach
            <div class="mt-3">
                {{ $reviews->appends(request()->toArray())->links() }}
            </div>
            @else
            <h1>По вашему запросу ничего не найдено, попробуйте заново</h1>
            @endif
        </div>
    </div>
@endsection