routes/web.php
<?php

use App\Http\Controllers\sessionController;
use App\Http\Controllers\UserReviewController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('main');
})->name('home');

Route::get('/register', 'RegistrationController@create');

Route::post('/register','RegistrationController@store');

Route::get('/login', 'SessionController@create')->name('login');

Route::post('/login', 'SessionController@store');

Route::get('/logout', 'SessionController@destroy');

Route::get('/reviews/create', 'ReviewController@create');

Route::post('/reviews/create', 'ReviewController@store');

Route::get('/reviews', 'ReviewController@index');

Route::get('/reviews/delete/{id}', 'ReviewController@delete');

Route::get('/reviews/show/{id}', 'ReviewController@show');

Route::get('/reviews/show/{id}/commentsexport', 'ExportController@commentExport');

Route::get('/myreviews/reviews/export', 'ExportController@reviewsExport');

Route::post('/reviews/show/{id}', 'ReviewCommentController@store');

Route::get('/reviews/sort/company', 'ReviewController@sortByCompany')->name('sortByCompany');

Route::get('/myreviews', 'UserReviewController@index')->name('myreviews');

Route::post('/myreviews', 'ImportController@importReview')->name('importReviews');

Route::get('/myreviews/sort/bydate', 'UserReviewController@sortByDate')->name('sortByDate');

Route::get('/myreviews/delete/{id}', 'UserReviewController@delete');

Route::resource('user_reviews', 'UserReviewController');

Route::get('/profile', 'ProfileController@index');

Route::post('/profile', 'ProfileController@update_avatar')->name('myprofile');

Route::get('/profile/redact', 'ProfileController@edit');

Route::post('/profile/redact', 'ProfileController@post');

Route::get('/profile/redactpassword', 'ProfileController@editPassword');

Route::post('/profile/redactpassword', 'ProfileController@updatePassword');

Route::get('/profile/review/id/{id}', 'ProfileController@profileReview');

Route::get('/reviews/search', 'ReviewController@search')->name('search');

app/Http/Controllers/UserReviewController.php
<?php

namespace App\Http\Controllers;

use App\Review;
use App\UserReview;
use App\ReviewImage;
use App\Country;
use App\Region;
use App\City;
use App\CompanyBranch;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Image;
use App\Events\SetGlobalvarEvent;
use Session;
use App\Events\UserReviewSortEvent;

class UserReviewController extends Controller
{

    public function __construct() {

        $this->middleware('auth');
        
    }

    public function index() {
        $reviews = Auth::user()->index->paginate(5);        
        return view('user_reviews.user_reviews',['reviews' => $reviews] );
    }

    public function sortByDate() {
        $sort_num = Session::get('review_sort');
        if($sort_num == 0){
            $reviews = Auth::user()->index->sortBy('created_at')->paginate(5);
            // $reviews->values()->all();
            event(new UserReviewSortEvent());            
        }else{
            $reviews = Auth::user()->index->sortByDesc('created_at')->paginate(5);
            // $reviews->values()->all()->paginate(5);            
            event(new SetGlobalVarEvent());            
        }
        // dd($reviews);
        return view('user_reviews.user_reviews', compact('reviews'));
    }

    public function edit($id) {
        $review = Review::find($id);
        $images = ReviewImage::where('review_id', $id)->get();
        $countries = Country::all();
        $regions = Region::all();
        $cities = City::all();
        $companies_branches = CompanyBranch::all();
        if(!$review) {
            return abort(404);
        }
        if($review->user_id == Auth::id())
        {
            return view('user_reviews.edit', compact('review', 'images', 'countries', 'regions', 'cities', 'companies_branches'));
        }
        else
        {
            return redirect('myreviews');
        }
        

    }

    public function update(Request $request, $id) {
        $request->validate([
            'title'=>'required',
            'body'=>'required',
            'country' => 'required|integer',
            'region' => 'required|integer',
            'city' => 'required|integer',
            'companies_branches' => 'required|integer'
        ]);
        $review = Review::find($id);
        $review->title = $request->get('title');
        $review->review_body = $request->get('body');
        $review->country_id = $request->country;
        $review->region_id = $request->region;
        $review->city_id = $request->city;
        $review->company_branch_id = $request->companies_branches;
        $review->save();

        $images = $request->file('review_photo');

        if($request->hasFile('review_photo')) {
            $imagesDelete = ReviewImage::where('review_id', $id)->get();
            foreach($imagesDelete as $image) {
                $image->delete();
            }
            $imageNameNumber = 0;
            foreach($images as $image) {
                $review_image = new ReviewImage();
                $review_image->review_id = $review->id;
                // $image = $req->file('review_photo');
                $filename = time() . ''.$imageNameNumber.'' . '.' . $image->getClientOriginalExtension();
                Image::make($image)->resize(640, 640)->save( public_path('uploads/photoes/' . $filename));
                $review_image->photo = $filename;
                $review_image->save();
                $imageNameNumber++;
            }            
        }
        
        return redirect()->route('myreviews');
    }

    public function delete($id) {
        $review = Review::find($id);
        $review->delete();
        return back();
    }
}

resources/views/user_reviews/edit.blade.php
@extends('layouts.app')

@section('title')
    Редактировать отзыв
@endsection

@section('content')
    <div class="container">
        <h1 class="">Напишите отзыв на компанию</h1>
        <div class="w-50 mx-auto">
        <form method="POST" enctype="multipart/form-data" action="{{ route('user_reviews.update', $review->id) }}">
                @method('PATCH')
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="title">Заголовок</label>
                <input class="form-control" value="{{$review->title}}" type="text" id="title" name="title">
                </div>

                <div class="form-group">
                    <label for="country">Выберите страну:</label>
                    <select class="form-control" name="country" id="country">
                        <option value="{{$review->countryBy->id}}" selected="selected">{{$review->countryBy->name}}</option>
                        @foreach ($countries as $country)
                            @if ($country->id == $review->countryBy->id)
                                @continue
                            @endif
                            <option value="{{$country->id}}">{{$country->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="region">Выберите область:</label>
                    <select class="form-control" name="region" id="region">
                        <option value="{{$review->regionBy->id}}" selected="selected">{{$review->regionBy->name}}</option>
                        @foreach ($regions as $region)
                            @if ($region->id == $review->regionBy->id)
                                @continue
                            @endif
                            <option value="{{$region->id}}">{{$region->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="city">Выберите город:</label>
                    <select class="form-control" name="city" id="city">
                        <option value="{{$review->cityBy->id}}" selected="selected">{{$review->cityBy->name}}</option>
                        @foreach ($cities as $city)
                            @if ($city->id == $review->cityBy->id)
                                @continue
                            @endif
                        <option value="{{$city->id}}">{{$city->name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="companies_branches">Выберите компанию:</label>
                    <select class="form-control" name="companies_branches" id="companies_branches">
                        <option value="{{$review->companyBy->id}}" selected="selected">{{$review->companyBy->company_name}}</option>
                        @foreach ($companies_branches as $company_branch)
                            @if ($company_branch->id == $review->companyBy->id)
                                @continue
                            @endif
                            <option value="{{$company_branch->id}}">{{$company_branch->company_name}}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label for="body">Отзыв</label>
                    <textarea class="form-control"  name="body" id="body" cols="30" rows="10">{!! $review->review_body!!}</textarea>
                </div>

                <div class="form-group">
                    <label for="review_photo">Фотографии:</label>
                    @foreach ($images as $image)
                    <div class="mt-2">
                        <img src="/uploads/photoes/{{ $image->photo }}" alt="">
                    </div>                
                    @endforeach
                <input class="form-control mt-2" type="file" id="review_photo" name="review_photo[]" value="" multiple>
                </div>

                <div class="form-group my-3">
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
            @include('inc.errors')
            </form>
        </div>
    </div>
@endsection

resources/views/user_reviews/user_reviews.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Мои отзывы</h1>
        <div>
            <a class="btn btn-primary mt-1" href="/myreviews/sort/bydate">Сортировать по дате публикации</a>
        </div>
        <div>
            <a class="btn btn-primary mt-2" href="/myreviews/reviews/export">Экспортировать комментарии к вашим отзывам</a>
        </div>
        <div>
            <form class="" action="/myreviews" method="POST" enctype="multipart/form-data">
                {{ csrf_field() }}
                <div class="form-group w-25 mt-5">
                    <input type="file" class="form-control" name="import_file">
                </div>
                <div class="form-group w-25 mt-2">
                    <button class="btn btn-primary form-control" type="submit">Импортировать отзывы</button>
                </div>
            </form>
        </div>
        @include('inc.errors')
        <div class="col-md-3 ml-auto">
            <a href="/reviews/create">Написать отзыв</a>
        </div>
        <div class="col-md-8 mr-auto">
            @foreach ($reviews as $review)
                <div class="card mt-3">
                    <div class="card-body">
                    <h5 class="card-title">{{ $review->title }}</h5>
                    <p class="card-text">{{ $review->review_body }}</p>
                    <label for="">Автор:</label>
                    <a href="/profile/review/id/{{$review->createdBy->id}}">{{  $review->createdBy->name  }}</a>
                    <a class="mb-1 ml-1 btn btn-primary" href="/reviews/show/{{$review->id}}">Подробнее</a>
                    <a href="{{ route('user_reviews.edit', $review->id )}}" class="btn btn-primary ml-5">Редактировать</a>
                    <a href="/myreviews/delete/{{$review->id}}" class="btn btn-primary ml-5">Удалить</a>
                    </div>
                    <div class="card-footer">
                        <span>Дата публикации: {{$review->created_at}}</span>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="mt-3">
            {{ $reviews->appends(request()->toArray())->links() }}
        </div>
    </div>
@endsection